name: Deploy to Heroku

on:
  push:
    branches:
      - '**'  # Triggers the workflow on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers the workflow on pull requests to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Heroku
      run: |
        git remote add heroku git@heroku.com:vovido-games.git
        git remote set-url heroku git@heroku.com:vovido-games.git

    - name: Debug SSH connection
      run: ssh -vT git@heroku.com


    - name: Push to Heroku
      run: |
        git push heroku HEAD:master


